plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\ikki2\\Documents\\事業\\AI×HPサービス\\AI×HP制作事業\\自家製麺いけだ_案件\\ikeda-ramen-deploy"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]